/**
 * Referral Level Configuration
 * 
 * ASSUMPTION: These percentages are not specified by the assessment.
 * They are configurable assumptions documented in the README.
 * 
 * Level income is calculated as a percentage of the daily ROI
 * generated by the downstream investor.
 */
export const REFERRAL_LEVELS = {
  1: 10,  // Direct referral: 10% of ROI
  2: 5,   // Level 2: 5% of ROI
  3: 3,   // Level 3: 3% of ROI
  4: 2,   // Level 4: 2% of ROI
  5: 1,   // Level 5: 1% of ROI
};

export const MAX_REFERRAL_DEPTH = Object.keys(REFERRAL_LEVELS).length;
